# Generated by Django 3.2.12 on 2022-04-03 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_book_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='created_at',
            field=models.DateTimeField(help_text='created time (this data)'),
        ),
        migrations.AlterField(
            model_name='book',
            name='date_of_issue',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(help_text='created time (this data)'),
        ),
    ]
